### ISSUE TITLE
cutscene crash (last update)

### ISSUE THREAD

**Issue by F1mpoPE** [VideoBotYT/Universe-Engine#1]
### Describe your bug here.

so, i know engine got deleted from gamebanana but i was fast enough for download it and in last update there is a weird bug that crashes game when cutscene plays. it happens always in same time (like: exacty in 00:10 cutscene time game crashes) but when i use playvideo script mid song nothing happens

https://github.com/user-attachments/assets/ac9cbf00-ca65-44f0-a01e-ee0722e18d7b

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no, i think. if we talk about soure, no. only mod files

**Comment by F1mpoPE** [comment]
FORGOT!!!
if you need video script, here:
function onStartCountdown()
    if not allowEnd and not seenCutscene then
        startVideo('Ending_2');
        allowEnd = true;
        return Function_Stop;
    end
    return Function_Continue;
end

**Comment by F1mpoPE** [comment]
ALSO FORGOT!!!
there is diferent script that i used but game was crashing too
local allowCountdown = false
function onStartCountdown()
	if not allowCountdown and isStoryMode and not seenCutscene then 
		startVideo('Ending_2');
		allowCountdown = true;
		return Function_Stop;
	end
	return Function_Continue;
end

**Comment by F1mpoPE** [comment]
wait. i don't have hxCodec installed. if this will be fixed then sorry

**Comment by F1mpoPE** [comment]
no, not fixed

**Comment by uwenalil** [comment]
hold on, leeme check this bug

**Comment by uwenalil** [comment]
It's a library issue, VideoBot has some bad libraries that really REALLY bugs out some stuff.
Source is now handled by me and the video works flawlessly and no crashes.
