### ISSUE TITLE
Builds compiled from source crashes when using any hitsounds

### ISSUE THREAD

**Issue by CharGoldenYT** [VideoBotYT/Universe-Engine#11]
### Describe your bug here.

Compiling from the github's source causes a crash due to the hitsound caching not reflecting the new filenames.

### Command Prompt/Terminal logs (if existing)

```bash
`./assets/sounds/Classic.ogg`

I'm not kidding, thats all it says.
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Yes. PauseSubState (Theres a seperate bug for that)

**Comment by uwenalil** [comment]
![image](https://github.com/user-attachments/assets/671d4529-39f7-4e36-a9c3-b354f8f9e3d8)
oh hold on i completely forgot about this
