### ISSUE TITLE
how am I supposed to download this without compiling?

### ISSUE THREAD

**Issue by daveandbambifan1234** [VideoBotYT/Universe-Engine#16]
### Describe your problem here.

a

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

a

**Comment by daveandbambifan1234** [comment]
found it out

**Comment by uwenalil** [comment]
this is the best issue

**Comment by moxie-coder** [comment]
kid named releases

**Comment by moxie-coder** [comment]
![image](https://github.com/user-attachments/assets/7cfe0ddb-bd42-491b-aa7b-58d0c2a02b5f)
