### ISSUE TITLE
Game crashes on Weekend 1

### ISSUE THREAD

**Issue by nahuelescrack** [VideoBotYT/Universe-Engine#19]
### Describe your bug here.

When i try to go into weekend one, at half the cutsene, the game closes, idk why, though, i downloaded the engine right today

If you need more info i can try and give you some but for now thats all the info i have

(i didnt mod anything, just vanilla universe engine)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Nope, i didnt edit anythinh

**Comment by nahuelescrack** [comment]
> did you get any error logs or something? if not, try running it from an command prompt

no, it just closed

How do i do that?

**Comment by moxie-coder** [comment]
> > did you get any error logs or something? if not, try running it from an command prompt
> 
> no, it just closed
> 
> How do i do that?

simply just put the name of the exe in command prompt, with .exe at the end too

**Comment by uwenalil** [comment]
dawg
