### ISSUE TITLE
uuhh bug fix

### ISSUE THREAD

**Issue by supernovae-is** [VideoBotYT/Universe-Engine#2]
### Describe your bug here.

so when i open stuff that have only inst it doesn't work and **crashes** its annoying and you need to fix because i dont like js engine.

### Command Prompt/Terminal logs (if existing)

```bash
Song.hx (line 143)
Song.hx (line 134)
FreeplayState.hx (line 430)
flixel/FlxState.hx (line 222)
flixel/FlxGame.hx (line 752)
flixel/FlxGame.hx (line 682)
flixel/FlxGame.hx (line 550)
openfl/events/EventDispatcher.hx (line 444)
openfl/display/DisplayObject.hx (line 1400)

Uncaught Error: Invalid field:validScore
Please report this error to the GitHub page: https://github.com/ShadowMario/FNF-PsychEngine

> Crash Handler written by: sqirra-rng
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

i didnt edit anything but i did port my mod

**Comment by VideoBotYT** [comment]
sorry that i see this pretty late but this is smth related to psych and idk how to fix but what i do know is that: make sure in your song chart file that needsVocals *or smth like that* is set to false

**Comment by uwenalil** [comment]
**library issue**
