### ISSUE TITLE
where do i put my modchart file??

### ISSUE THREAD

**Issue by Bezizeja** [VideoBotYT/Universe-Engine#21]
### Describe your problem here.

yessss

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

nope

**Comment by CharGoldenYT** [comment]
I would assume the same place as your song chart

**Comment by uwenalil** [comment]
same place as your song chart

**Comment by Bezizeja** [comment]
yeah i did but it didnt work

**Comment by VideoBotYT** [comment]
> yeah i did but it didnt work

fixes

make sure the modchart json file is called modchart and that it is a json file

make sure it's in the correct data folder

make sure that modcharts are on
