### ISSUE TITLE
I messed up fully, help need!

### ISSUE THREAD

**Issue by F1mpoPE** [VideoBotYT/Universe-Engine#25]
### Describe your problem here.

when i tried to make script that changes keybinds i run a test and now
it shows this every time i start engine

https://github.com/user-attachments/assets/3fb228a3-fd4c-4708-bc8d-f273757a6018

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by F1mpoPE** [comment]
as you can see this script affected on all universe engines
btw script:
function onSongStart()
	runHaxeCode([[
					 {
						ClientPrefs.keyBinds.set(('note_left','A')
						ClientPrefs.saveSettings();
					}
						return false;
				]])
end

i put this in one song, and when bug happened i removed it in folder where was all this fnf mods

**Comment by uwenalil** [comment]
Go to
`C:\Users\{your user here}\AppData\Roaming\Universe`
And delete `controls_v2.sol`.
This will delete your keybinds.

**Comment by F1mpoPE** [comment]
woah, that was fast, thanks!
