### ISSUE TITLE
this engine made me become a fa##ot

### ISSUE THREAD

**Issue by imCherryOWO** [VideoBotYT/Universe-Engine#26]
### Describe your bug here.

help when i played universe engine i became a fa##ot and i cant stop!!!!!!!!!!

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by uwenalil** [comment]
This is just straight up unfunny.

**Comment by moxie-coder** [comment]
haha, very funny, screw you

**Comment by imCherryOWO** [comment]
real
