### ISSUE TITLE
how do I get the build without compiling?

### ISSUE THREAD

**Issue by daveandbambifan1234** [VideoBotYT/Universe-Engine#3]
### Describe your problem here.

a

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

e

**Comment by daveandbambifan1234** [comment]
uhm nvm

**Comment by uwenalil** [comment]
wow didn't even have the chance to help
