### ISSUE TITLE
I pressed a random area and this:

### ISSUE THREAD

**Issue by daveandbambifan1234** [VideoBotYT/Universe-Engine#4]
### Describe your bug here.

![image](https://github.com/user-attachments/assets/14881169-750f-438e-9b70-2a3880743e0d)

### Command Prompt/Terminal logs (if existing)

```bash
look at the image
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

none

**Comment by VideoBotYT** [comment]
yeah thats a known issue it's fixed in the next update

**Comment by uwenalil** [comment]
Fixed by me, game trying to detect if you're trying to click the pixel's note or not and the game freaks out and just crashes.
