### ISSUE TITLE
adding songs to this engine is absolute hell

### ISSUE THREAD

**Issue by daveandbambifan1234** [VideoBotYT/Universe-Engine#5]
### Describe your bug here.

you can't add songs cuz it keeps crashing

### Command Prompt/Terminal logs (if existing)

```bash
a
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

a

**Comment by daveandbambifan1234** [comment]
![image](https://github.com/user-attachments/assets/89f654ea-0907-4394-a3ee-8aca664ce7ca)

**Comment by VideoBotYT** [comment]
make sure that in your song chart file that needsVoices *or smth like that* is set to false

**Comment by uwenalil** [comment]
**once again LIBRARY ISSUE VIDEOBOT.**
