### ISSUE TITLE
assets/fonts/funkin.ttf does not exist in source

### ISSUE THREAD

**Issue by CharGoldenYT** [VideoBotYT/Universe-Engine#6]
### Describe your bug here.

Basically, the source does not include the "funkin.ttf" file in assets/fonts and makes the text look like this
![image](https://github.com/user-attachments/assets/045672c4-89d9-40b4-b0b8-5867f5b7da64)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Nope.

**Comment by CharGoldenYT** [comment]
Wait nvm

it's all in the mods folder (Which isn't included in source.)

**Comment by VideoBotYT** [comment]
easy fix just copy the mods folder from the prebuild game the reason why it isn't there is bc if it was in example mods and u changed smth in the UE directory in the games files and u compile the game it will override it.
